---
collections:
  - name: ansible.controller
  - name: ansible.platform
  - name: https://github.com/redhat-cop/infra.aap_configuration
    type: git
    version: devel
  - name: redhat.rhel_system_roles
  - name: community.aws
  - name: community.general
  - name: community.mysql
  - name: containers.podman
  - name: community.crypto
  - name: chocolatey.chocolatey
  - name: community.windows
